from pathlib import Path

base=Path('.github/prepare_30163.py')
exec(compile(base.read_text(),str(base),'exec'),{'__name__':'__main__','__file__':str(base)})

def rep(path,old,new,label):
 p=Path(path);s=p.read_text()
 if s.count(old)!=1:raise SystemExit('3.0.164 target '+label+' count '+str(s.count(old)))
 p.write_text(s.replace(old,new,1))

rep('app/build.gradle','versionCode 30163','versionCode 30164','code')
rep('app/build.gradle',"versionName '3.0.163'","versionName '3.0.164'",'name')
rep('app/src/main/AndroidManifest.xml','iCE Onhand 3.0.163','iCE Onhand 3.0.164','manifest')
rep('app/src/main/java/com/iceinventory/onhand/MainActivity.java','Onhand Inventory 3.0.163','Onhand Inventory 3.0.164','header')

Path('app/src/main/java/com/iceinventory/onhand/MonthlyUnmatchedXlsxWriter.java').write_text(r'''package com.iceinventory.onhand;
import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.zip.*;
public final class MonthlyUnmatchedXlsxWriter{
 private MonthlyUnmatchedXlsxWriter(){}
 public static final class Row{public String barcode="",description="",users="",locations="";public double quantity;}
 public static void write(OutputStream out,String customer,String date,List<Row> data)throws IOException{
  StringBuilder x=new StringBuilder();int r=1;row(x,r++,new String[]{"MISSING / NEW ITEMS — CLIENT ACTION REQUIRED","","","",""},true);
  row(x,r++,new String[]{"CUSTOMER",customer,"INVENTORY DATE",date,""},false);r++;
  row(x,r++,new String[]{"BARCODE","QUANTITY","DESCRIPTION","COUNTER / USER FILE AND QUANTITY","LOCATIONS"},true);
  double total=0;for(Row a:data){total+=a.quantity;rowStart(x,r);text(x,0,r,a.barcode,0);number(x,1,r,a.quantity,0);text(x,2,r,a.description,0);text(x,3,r,a.users,0);text(x,4,r,a.locations,0);rowEnd(x);r++;}
  rowStart(x,r);text(x,0,r,"TOTAL MISSING QUANTITY",1);number(x,1,r,total,1);text(x,2,r,"Add or correct these products in Petrosoft after inventory.",1);rowEnd(x);
  ZipOutputStream z=new ZipOutputStream(out);put(z,"[Content_Types].xml",types());put(z,"_rels/.rels",rels());put(z,"xl/workbook.xml",book());put(z,"xl/_rels/workbook.xml.rels",bookrels());put(z,"xl/styles.xml",styles());
  String sheet="<?xml version=\"1.0\" encoding=\"UTF-8\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetViews><sheetView workbookViewId=\"0\"><pane ySplit=\"4\" topLeftCell=\"A5\" state=\"frozen\"/></sheetView></sheetViews><cols><col min=\"1\" max=\"1\" width=\"20\" customWidth=\"1\"/><col min=\"2\" max=\"2\" width=\"12\" customWidth=\"1\"/><col min=\"3\" max=\"3\" width=\"42\" customWidth=\"1\"/><col min=\"4\" max=\"4\" width=\"55\" customWidth=\"1\"/><col min=\"5\" max=\"5\" width=\"28\" customWidth=\"1\"/></cols><sheetData>"+x+"</sheetData><autoFilter ref=\"A4:E"+r+"\"/></worksheet>";put(z,"xl/worksheets/sheet1.xml",sheet);z.finish();z.flush();
 }
 private static void row(StringBuilder x,int r,String[] v,boolean bold){rowStart(x,r);for(int i=0;i<v.length;i++)text(x,i,r,v[i],bold?1:0);rowEnd(x);}
 private static void rowStart(StringBuilder x,int r){x.append("<row r=\"").append(r).append("\">");}private static void rowEnd(StringBuilder x){x.append("</row>");}
 private static void text(StringBuilder x,int c,int r,String v,int s){x.append("<c r=\"").append(ref(c,r)).append("\" t=\"inlineStr\"");if(s>0)x.append(" s=\"").append(s).append("\"");x.append("><is><t xml:space=\"preserve\">").append(xml(v)).append("</t></is></c>");}
 private static void number(StringBuilder x,int c,int r,double v,int s){x.append("<c r=\"").append(ref(c,r)).append("\"");if(s>0)x.append(" s=\"").append(s).append("\"");x.append("><v>").append(QuantityMath.format(v)).append("</v></c>");}
 private static String ref(int c,int r){int n=c+1;StringBuilder b=new StringBuilder();while(n>0){int q=(n-1)%26;b.insert(0,(char)('A'+q));n=(n-1)/26;}return b.toString()+r;}
 private static String xml(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;").replace("'","&apos;");}
 private static void put(ZipOutputStream z,String n,String v)throws IOException{z.putNextEntry(new ZipEntry(n));z.write(v.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
 private static String types(){return "<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/></Types>";}
 private static String rels(){return "<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>";}
 private static String book(){return "<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Missing New Items\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>";}
 private static String bookrels(){return "<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/></Relationships>";}
 private static String styles(){return "<?xml version=\"1.0\"?><styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><fonts count=\"2\"><font><sz val=\"11\"/><name val=\"Calibri\"/></font><font><b/><sz val=\"11\"/><name val=\"Calibri\"/></font></fonts><fills count=\"3\"><fill><patternFill patternType=\"none\"/></fill><fill><patternFill patternType=\"gray125\"/></fill><fill><patternFill patternType=\"solid\"><fgColor rgb=\"FFFFD700\"/></patternFill></fill></fills><borders count=\"1\"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count=\"1\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/></cellStyleXfs><cellXfs count=\"2\"><xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/><xf numFmtId=\"0\" fontId=\"1\" fillId=\"2\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/></cellXfs></styleSheet>";}
}''')

p=Path('app/src/main/java/com/iceinventory/onhand/MonthlyInventoryActivity.java');s=p.read_text()
s=s.replace('SAVE_UNMATCHED=5111;','SAVE_UNMATCHED=5111;',1)
s=s.replace('private boolean sourceReady,masterCreated,onHandCreated,deviceLoaded,testScanPassed,countsReady,validated,countLaunchPending,restoringMonthly,combinedExported,clientExported,auditExported;','private boolean sourceReady,masterCreated,onHandCreated,deviceLoaded,testScanPassed,countsReady,validated,exceptionsApproved,missingItemsExported,countLaunchPending,restoringMonthly,combinedExported,clientExported,auditExported;',1)
s=s.replace('private Button chooseSource,saveMaster,saveOnHand,loadDevice,shareOnHand,chooseCounts,saveCombined,saveClient,saveAudit,adjustCount,closeProject,saveCategory,saveCigarettes,saveUnmatched;','private Button chooseSource,saveMaster,saveOnHand,loadDevice,shareOnHand,chooseCounts,saveCombined,saveClient,saveAudit,adjustCount,closeProject,saveCategory,saveCigarettes,saveUnmatched,approveExceptions;',1)
s=s.replace('saveUnmatched=button("REVIEW / EXPORT UNMATCHED ITEMS — TXT");saveUnmatched.setTextColor(Color.BLACK);saveUnmatched.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(255,193,7)));saveUnmatched.setOnClickListener(v->create(SAVE_UNMATCHED,"text/plain",base()+" UNMATCHED ITEMS-"+day()+".txt"));root.addView(saveUnmatched,params(58));','approveExceptions=button("APPROVE MISSING ITEMS & COMPLETE INVENTORY");approveExceptions.setTextColor(Color.BLACK);approveExceptions.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(255,193,7)));approveExceptions.setOnClickListener(v->approveMissingItems());root.addView(approveExceptions,params(62));\n        saveUnmatched=button("EXPORT MISSING / NEW ITEMS — EXCEL");saveUnmatched.setTextColor(Color.BLACK);saveUnmatched.setBackgroundTintList(android.content.res.ColorStateList.valueOf(Color.rgb(255,193,7)));saveUnmatched.setOnClickListener(v->create(SAVE_UNMATCHED,"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",base()+" MISSING NEW ITEMS-"+day()+".xlsx"));root.addView(saveUnmatched,params(58));',1)
s=s.replace('sourceTotal=combinedTotal=clientTotal=0;validated=false;','sourceTotal=combinedTotal=clientTotal=0;validated=false;exceptionsApproved=false;missingItemsExported=false;',1)
s=s.replace('validated=countFiles.size()==uris.size()&&QuantityMath.equal(sourceTotal,combinedTotal)&&QuantityMath.equal(combinedTotal,clientTotal)&&unmatched.isEmpty();countsReady=true;','validated=countFiles.size()==uris.size()&&QuantityMath.equal(sourceTotal,combinedTotal)&&QuantityMath.equal(combinedTotal,clientTotal)&&unmatched.isEmpty();exceptionsApproved=unmatched.isEmpty();missingItemsExported=unmatched.isEmpty();countsReady=true;',1)
s=s.replace('else if(request==SAVE_UNMATCHED){if(unmatched.isEmpty())throw new Exception("There are no unmatched items");use.write(unmatchedText().getBytes(StandardCharsets.UTF_8));}','else if(request==SAVE_UNMATCHED){if(unmatched.isEmpty())throw new Exception("There are no missing items");MonthlyUnmatchedXlsxWriter.write(use,base(),clientDate(),missingRows());missingItemsExported=true;}',1)
anchor='    private String unmatchedText(){'
methods='''    private double unmatchedQuantity(){double n=0;for(String code:unmatched)n+=combined.getOrDefault(code,0d);return n;}
    private ArrayList<MonthlyUnmatchedXlsxWriter.Row> missingRows(){ArrayList<MonthlyUnmatchedXlsxWriter.Row> rows=new ArrayList<>();for(String code:unmatched){UnmatchedDetail d=countDetails.get(code);MonthlyUnmatchedXlsxWriter.Row r=new MonthlyUnmatchedXlsxWriter.Row();r.barcode=code;r.quantity=combined.getOrDefault(code,0d);r.description=d==null?"":d.description;r.users=sourceText(d);r.locations=d==null?"":android.text.TextUtils.join(", ",d.locations);rows.add(r);}return rows;}
    private void approveMissingItems(){if(unmatched.isEmpty()){Toast.makeText(this,"There are no missing items to approve",Toast.LENGTH_LONG).show();return;}double missing=unmatchedQuantity();boolean reconciled=QuantityMath.equal(sourceTotal,combinedTotal)&&QuantityMath.equal(combinedTotal,clientTotal+missing);if(!reconciled){fail("Totals do not reconcile. Missing items cannot be approved.");return;}new android.app.AlertDialog.Builder(this).setTitle("Complete Inventory With Missing Items?").setMessage("The normal Petrosoft Customer Import Excel will contain "+QuantityMath.format(clientTotal)+" matched units.\\n\\nThe separate Missing / New Items Excel will contain "+QuantityMath.format(missing)+" units across "+unmatched.size()+" barcodes for the client to add or adjust after inventory.\\n\\nThe full audit total remains "+QuantityMath.format(combinedTotal)+" units. Nothing is deleted from the audit record.").setNegativeButton("GO BACK",null).setPositiveButton("APPROVE & CONTINUE",(d,w)->{exceptionsApproved=true;validated=true;showValidation();setEnabledState();Toast.makeText(this,"Approved. Export both the Customer Import Excel and Missing / New Items Excel.",Toast.LENGTH_LONG).show();}).show();}

'''
if anchor not in s:raise SystemExit('3.0.164 methods anchor missing')
s=s.replace(anchor,methods+anchor,1)

start=s.find('    private void showValidation(){');end=s.find('\n    private void showProgress()',start)
if start<0 or end<0:raise SystemExit('3.0.164 showValidation missing')
show='''    private void showValidation(){StringBuilder b=new StringBuilder();if(validated&&unmatched.isEmpty())b.append("PASS — CLIENT REPORT READY");else if(validated)b.append("PASS WITH DOCUMENTED EXCEPTIONS — EXPORT TWO CLIENT REPORTS");else b.append("FAILED VALIDATION — ACTION REQUIRED");b.append("\\n\\nUser count files: ").append(countFiles.size()).append("\\nFull audit total: ").append(QuantityMath.format(combinedTotal)).append("\\nPetrosoft matched total: ").append(QuantityMath.format(clientTotal)).append("\\nMissing/new item total: ").append(QuantityMath.format(unmatchedQuantity())).append("\\nCombined unique barcodes: ").append(combined.size()).append("\\nFinal Petrosoft GTIN rows: ").append(clientRows.size()).append("\\nMissing/new barcodes: ").append(unmatched.size());if(!unmatched.isEmpty()){b.append("\\n\\nMISSING / NEW ITEMS:");for(String code:unmatched){UnmatchedDetail d=countDetails.get(code);b.append("\\n\\n").append(code).append("  •  Qty ").append(QuantityMath.format(combined.getOrDefault(code,0d)));if(d!=null&&!d.description.isEmpty())b.append("\\n").append(d.description);b.append("\\nFrom: ").append(sourceText(d));if(d!=null&&!d.locations.isEmpty())b.append("\\nLocation: ").append(android.text.TextUtils.join(", ",d.locations));}if(!exceptionsApproved)b.append("\\n\\nPress APPROVE MISSING ITEMS & COMPLETE INVENTORY. These items will be excluded only from the Petrosoft import and documented in a separate Excel report.");else b.append("\\n\\nAPPROVED: Export the Customer Import Excel and the Missing / New Items Excel. The client can add or adjust these products after inventory.");}b.append("\\n\\nLocked Petrosoft columns:\\nGTIN, QUANTITY, CATEGORY_ID, RETAIL, DESCRIPTION, COST, DATE, TIME, SECTION");status.setText(b.toString());status.setTextColor(validated?Color.rgb(120,255,140):Color.rgb(255,130,130));}'''
s=s[:start]+show+s[end:]
s=s.replace('if(saveUnmatched!=null)saveUnmatched.setEnabled(countsReady&&!unmatched.isEmpty());if(adjustCount!=null)','if(saveUnmatched!=null)saveUnmatched.setEnabled(countsReady&&!unmatched.isEmpty());if(approveExceptions!=null)approveExceptions.setEnabled(countsReady&&!unmatched.isEmpty()&&!exceptionsApproved);if(adjustCount!=null)',1)
s=s.replace('if(!(combinedExported&&clientExported&&auditExported)){fail("Export the combined TXT, Petrosoft client Excel, and verification report before closing");return;}','if(!(combinedExported&&clientExported&&auditExported&&(unmatched.isEmpty()||missingItemsExported))){fail("Export the combined TXT, Petrosoft client Excel, verification report, and any Missing / New Items Excel before closing");return;}',1)
s=s.replace('closeProject.setEnabled(combinedExported&&clientExported&&auditExported);','closeProject.setEnabled(combinedExported&&clientExported&&auditExported&&(unmatched.isEmpty()||missingItemsExported));',1)
p.write_text(s)

checks={'version':"versionName '3.0.164'" in Path('app/build.gradle').read_text(),'approve':'APPROVE MISSING ITEMS & COMPLETE INVENTORY' in s,'excel':'MonthlyUnmatchedXlsxWriter.write' in s,'reconcile':'clientTotal+missing' in s}
bad=[k for k,v in checks.items() if not v]
if bad:raise SystemExit('3.0.164 checks failed: '+', '.join(bad))
print('Prepared iCE OnHand 3.0.164: approve documented missing items and complete inventory with two Excel deliverables')
