from pathlib import Path
import runpy

# Preserve every approved 3.0.50 behavior first.
runpy.run_path('.github/prepare_3050.py', run_name='__main__')

# --- InventoryAdapter: double-tap any visible item to highlight/select it.
# Once highlighted yellow, a single tap on its description/details adds +1.
# A single tap on a non-highlighted description opens the quantity-only edit dialog.
p=Path('app/src/main/java/com/iceinventory/onhand/InventoryAdapter.java')
s=p.read_text()

s=s.replace('import android.view.Gravity;\n', 'import android.view.Gravity;\nimport android.view.GestureDetector;\nimport android.view.MotionEvent;\n', 1)

old='''        void onEdit(InventoryDb.Row row);\n        String imageUrlFor(String barcode);\n'''
new='''        void onEdit(InventoryDb.Row row);\n        void onHighlight(InventoryDb.Row row);\n        String imageUrlFor(String barcode);\n'''
if old not in s: raise SystemExit('3.0.51 target missing: listener interface')
s=s.replace(old,new,1)

old='''        center.setClickable(active);\n        center.setFocusable(active);\n'''
new='''        center.setClickable(true);\n        center.setFocusable(true);\n'''
if old not in s: raise SystemExit('3.0.51 target missing: center clickable generated by 3.0.49')
s=s.replace(old,new,1)

old='''        // Quick +1 is allowed only on the currently highlighted yellow row.\n        // Touching a description on any other row must never change its quantity.\n        if(active)center.setOnClickListener(v->listener.onAddOne(r));\n'''
new='''        // Double-tap selects/highlights any visible row. Once it is yellow, a single\n        // tap on its description/details is the protected quick +1 action.\n        // A single tap on a non-highlighted row opens the quantity-only edit dialog.\n        GestureDetector detector=new GestureDetector(context,new GestureDetector.SimpleOnGestureListener(){\n            @Override public boolean onDown(MotionEvent e){return true;}\n            @Override public boolean onSingleTapConfirmed(MotionEvent e){\n                if(active)listener.onAddOne(r);else listener.onEdit(r);\n                return true;\n            }\n            @Override public boolean onDoubleTap(MotionEvent e){\n                listener.onHighlight(r);\n                return true;\n            }\n        });\n        center.setOnTouchListener((v,e)->detector.onTouchEvent(e));\n'''
if old not in s: raise SystemExit('3.0.51 target missing: highlighted-only quick add')
s=s.replace(old,new,1)
p.write_text(s)

# --- MainActivity: Edit Count becomes quantity-add-only; imported file renames inventory.
p=Path('app/src/main/java/com/iceinventory/onhand/MainActivity.java')
s=p.read_text()

old='''    @Override public void onEdit(InventoryDb.Row r) {\n        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);\n        TextView info=text(r.barcode,15,Color.BLACK,true);box.addView(info);\n        EditText d=new EditText(this);d.setHint("Description");d.setText(r.description==null?"":r.description);box.addView(d);\n        EditText price=new EditText(this);price.setHint("Price");price.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);price.setText(r.price==null?"":r.price);box.addView(price);\n        EditText q=new EditText(this);q.setHint("Quantity");q.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_SIGNED);q.setText(String.valueOf(r.quantity));box.addView(q);\n        Spinner loc=new Spinner(this);loc.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,db.locations()));\n        List<String> locs=db.locations();int sel=Math.max(0,locs.indexOf(r.location));loc.setSelection(sel);box.addView(loc);\n        Button multiply=new Button(this);multiply.setText("Add Quantity / Cases");multiply.setAllCaps(false);multiply.setBackgroundColor(Color.rgb(20,75,205));multiply.setTextColor(Color.WHITE);\n        box.addView(multiply,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(50)));\n\n        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Edit Count").setView(box)\n                .setPositiveButton("Save",(dd,w)->{\n                    int nq=r.quantity;try{nq=Integer.parseInt(q.getText().toString().trim());}catch(Exception ignored){}\n                    String nl=loc.getSelectedItem()==null?"Main":loc.getSelectedItem().toString();\n                    db.addLocation(nl);db.updateItem(r.id,d.getText().toString(),price.getText().toString().replace("$","").trim(),nq,nl);refreshList();\n                })\n                .setNeutralButton("Delete",(dd,w)->{db.deleteItem(r.id);refreshList();})\n                .setNegativeButton("Cancel",null).create();\n        multiply.setOnClickListener(v->{dialog.dismiss();launchQuantity(r);});\n        dialog.show();\n    }\n'''
new='''    @Override public void onEdit(InventoryDb.Row r) {\n        LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(6),dp(18),0);\n        String desc=r.description==null?"":r.description;\n        String price=(r.price==null||r.price.trim().isEmpty())?"":"$"+r.price.trim();\n        String details="Barcode: "+r.barcode+"\\nDescription: "+desc+"\\nPrice: "+price+"\\nCurrent Qty: "+r.quantity+"\\nLocation: "+(r.location==null?"Main":r.location);\n        TextView info=text(details,15,Color.BLACK,false);box.addView(info);\n        EditText addQty=new EditText(this);\n        addQty.setHint("Quantity to add");\n        addQty.setInputType(InputType.TYPE_CLASS_NUMBER);\n        addQty.setSingleLine(true);\n        box.addView(addQty);\n\n        AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Add Quantity").setView(box)\n                .setPositiveButton("Add",null)\n                .setNegativeButton("Cancel",null).create();\n        dialog.setOnShowListener(x->{\n            dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{\n                String raw=addQty.getText().toString().trim();\n                int amount=0;try{amount=Integer.parseInt(raw);}catch(Exception ignored){}\n                if(amount<=0){toast("Enter quantity to add");addQty.requestFocus();showKeyboard(addQty);return;}\n                db.incrementQuantity(r.id,amount);lastBarcode=r.barcode;refreshList();dialog.dismiss();\n            });\n            addQty.requestFocus();addQty.postDelayed(()->showKeyboard(addQty),100);\n        });\n        dialog.show();\n    }\n\n    @Override public void onHighlight(InventoryDb.Row r) {\n        if(r==null)return;\n        lastBarcode=r.barcode==null?"":r.barcode;\n        applyFilter();\n    }\n'''
if old not in s: raise SystemExit('3.0.51 target missing: edit count dialog')
s=s.replace(old,new,1)

# 3.0.46 already remembers the import filename for export. Extend that behavior so the\n# visible inventory/session name also follows the imported file name after a successful import.
old='''            int imported=TabTextUtils.importRows(br,db,sessionId,prefs(),prefs().getBoolean(KEY_AUTO_GTIN,false));\n            refreshLocations();refreshList();toast("Imported "+imported+" tab-delimited TXT rows");\n'''
new='''            int imported=TabTextUtils.importRows(br,db,sessionId,prefs(),prefs().getBoolean(KEY_AUTO_GTIN,false));\n            if(imported>0&&!selectedName.isEmpty()) {\n                String inventoryName=selectedName.trim();\n                int dot=inventoryName.lastIndexOf('.');if(dot>0)inventoryName=inventoryName.substring(0,dot);\n                if(!inventoryName.isEmpty()) {\n                    db.renameSession(sessionId,inventoryName);\n                    sessionName=inventoryName;\n                }\n            }\n            refreshLocations();refreshList();toast("Imported "+imported+" tab-delimited TXT rows");\n'''
if old not in s: raise SystemExit('3.0.51 target missing: imported filename/session rename')
s=s.replace(old,new,1)
p.write_text(s)

# --- InventoryDb: allow the active inventory/session title to be renamed after import.
p=Path('app/src/main/java/com/iceinventory/onhand/InventoryDb.java')
s=p.read_text()
marker='''    public List<Session> sessions() {\n'''
helper='''    public void renameSession(long id,String name) {\n        if(id<=0||name==null||name.trim().isEmpty())return;\n        ContentValues cv=new ContentValues();\n        cv.put("name",name.trim());\n        getWritableDatabase().update("sessions",cv,"id=?",new String[]{String.valueOf(id)});\n    }\n\n'''
if marker not in s: raise SystemExit('3.0.51 target missing: sessions marker')
s=s.replace(marker,helper+marker,1)
p.write_text(s)

print('Prepared iCE Onhand 3.0.51: quantity-only edit + double-tap highlight + import renames inventory')
